install: gradle wrapper --gradle-version 4.4

language: java

addons:
  sonarcloud:
    organization: "toberkoe-github"
    token:
      secure: $SONAR_TOKEN

jdk:
  - oraclejdk9

script:
  - ./gradlew clean test jacocoJUnit5TestReport sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'